#!/usr/bin/env bash

set -euo pipefail

rm -rf built
cp -r assets built

touch built/web/packages.js

pushd src || exit 1

declare -a packages=("formats" "renderer" "storage" "workspace")

for i in "${packages[@]}"
do

    pushd "$i" || exit 1
    
    cargo test -- --test-threads 3

done
