[package]
name = "hc_network"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
hc_utilities = { path = "../hc_utilities" }
futures = "0.3"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
reqwest = "0.12"
dirs = "5.0"
cfg-if = "1.0"
