#!/usr/bin/env bash

set -euo pipefail

wasm=false
if [[ "$1" == "--wasm" ]]; then
    wasm=true
    shift
fi

linuxcli=false
if [[ "${1-}" == "--linux-cli" ]]; then
    linuxcli=true
    shift
fi

rm -rf built
cp -r assets built
cp -r built/shared-data built/linux-cli/
cp -r built/shared-data built/web/

mkdir -p ~/.heartcollective
cp -r built/shared-data ~/.heartcollective/

touch built/web/packages.js

declare -a packages=("hc_formats" "hc_io" "hc_network" "hc_renderer" "hc_storage" "hc_workspace" "hc_utilities")

for i in "${packages[@]}"
do

    pushd "$i" || exit 1
    
    # cargo test -- --test-threads 3
    [[ "$wasm" == true ]] && wasm-pack build --target web
    [[ "$wasm" == true ]] && cp -r pkg ../built/web/lib/"$i"
    echo "import * as $i from \"./lib/$i/$i.js\";" >> ../built/web/packages.js
    
    [[ "$linuxcli" == true ]] && cargo build
    
    popd || exit 1

done

echo 'async function run() {' >> built/web/packages.js

for i in "${packages[@]}"
do

    # NOTE this is debug build for now
    [[ -f "$i/target/debug/$i" ]] && cp "$i/target/debug/$i" built/linux-cli/

    echo "await $i.default();" >> built/web/packages.js

done

echo 'hc_workspace.start();' >> built/web/packages.js
echo '}' >> built/web/packages.js
echo 'run();' >> built/web/packages.js
