#!/usr/bin/env bash

set -euo pipefail

rm -rf built
cp -r assets built
cp -r built/shared-data built/linux-cli/
cp -r built/shared-data built/web/

mkdir -p ~/.heartcore
cp -r built/shared-data ~/.heartcore/

touch built/web/packages.js

declare -a packages=("hc_formats" "hc_network" "hc_renderer" "hc_storage" "hc_workspace" "hc_utilities")

for i in "${packages[@]}"
do

    pushd "$i" || exit 1
    
    # cargo test -- --test-threads 3
    wasm-pack build --target web
    cp -r pkg ../built/web/lib/"$i"
    echo "import * as $i from \"./lib/$i/$i.js\";" >> ../built/web/packages.js
    popd || exit 1

done

pushd hc_workspace || exit 1
cargo build
popd || exit 1
# NOTE this is debug build for now
cp hc_workspace/target/debug/workspace built/linux-cli/

echo 'async function run() {' >> built/web/packages.js

for i in "${packages[@]}"
do

    echo "await $i.default();" >> built/web/packages.js

done

echo 'hc_workspace.start();' >> built/web/packages.js
echo '}' >> built/web/packages.js
echo 'run();' >> built/web/packages.js
