[package]
name = "hc_utilities"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
wasm-bindgen = "0.2"
cfg-if = "1.0"

[target.'cfg(not(target_family = "wasm"))'.dependencies]
duct = "0.13"
nix = { version = "0.29", features = ["fs"] }
tempfile = "3.14"

